SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for aio_country
-- ----------------------------
DROP TABLE IF EXISTS `aio_country`;
CREATE TABLE `aio_country`  (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `iso` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `iName` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `niceName` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `trName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `iso3` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `numcode` smallint(100) NULL DEFAULT NULL,
  `phonecode` int(100) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 240 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of aio_country
-- ----------------------------
INSERT INTO `aio_country` VALUES (1, 'AF', 'AFGHANISTAN', 'Afghanistan', 'Afganistan', 'AFG', 4, 93);
INSERT INTO `aio_country` VALUES (2, 'AL', 'ALBANIA', 'Albania', 'Arnavutluk', 'ALB', 8, 355);
INSERT INTO `aio_country` VALUES (3, 'DZ', 'ALGERIA', 'Algeria', 'Cezayir', 'DZA', 12, 213);
INSERT INTO `aio_country` VALUES (4, 'AS', 'AMERICAN SAMOA', 'American Samoa', 'Amerikan Samoası', 'ASM', 16, 1684);
INSERT INTO `aio_country` VALUES (5, 'AD', 'ANDORRA', 'Andorra', 'Andorra', 'AND', 20, 376);
INSERT INTO `aio_country` VALUES (6, 'AO', 'ANGOLA', 'Angola', 'Angora', 'AGO', 24, 244);
INSERT INTO `aio_country` VALUES (7, 'AI', 'ANGUILLA', 'Anguilla', 'Anguilla', 'AIA', 660, 1264);
INSERT INTO `aio_country` VALUES (8, 'AQ', 'ANTARCTICA', 'Antarctica', 'Antarktika', NULL, NULL, 0);
INSERT INTO `aio_country` VALUES (9, 'AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'Antigua ve Barbuda', 'ATG', 28, 1268);
INSERT INTO `aio_country` VALUES (10, 'AR', 'ARGENTINA', 'Argentina', 'Arjantin', 'ARG', 32, 54);
INSERT INTO `aio_country` VALUES (11, 'AM', 'ARMENIA', 'Armenia', 'Ermenistan', 'ARM', 51, 374);
INSERT INTO `aio_country` VALUES (12, 'AW', 'ARUBA', 'Aruba', 'Aruba', 'ABW', 533, 297);
INSERT INTO `aio_country` VALUES (13, 'AU', 'AUSTRALIA', 'Australia', 'Avustralya', 'AUS', 36, 61);
INSERT INTO `aio_country` VALUES (14, 'AT', 'AUSTRIA', 'Austria', 'Avusturya', 'AUT', 40, 43);
INSERT INTO `aio_country` VALUES (15, 'AZ', 'AZERBAIJAN', 'Azerbaijan', 'Azerbeycan', 'AZE', 31, 994);
INSERT INTO `aio_country` VALUES (16, 'BS', 'BAHAMAS', 'Bahamas', 'Bahamalar', 'BHS', 44, 1242);
INSERT INTO `aio_country` VALUES (17, 'BH', 'BAHRAIN', 'Bahrain', 'Bahreyn', 'BHR', 48, 973);
INSERT INTO `aio_country` VALUES (18, 'BD', 'BANGLADESH', 'Bangladesh', 'Bangladeş', 'BGD', 50, 880);
INSERT INTO `aio_country` VALUES (19, 'BB', 'BARBADOS', 'Barbados', 'Barbados', 'BRB', 52, 1246);
INSERT INTO `aio_country` VALUES (20, 'BY', 'BELARUS', 'Belarus', 'Belarus', 'BLR', 112, 375);
INSERT INTO `aio_country` VALUES (21, 'BE', 'BELGIUM', 'Belgium', 'Belçika', 'BEL', 56, 32);
INSERT INTO `aio_country` VALUES (22, 'BZ', 'BELIZE', 'Belize', 'Belize', 'BLZ', 84, 501);
INSERT INTO `aio_country` VALUES (23, 'BJ', 'BENIN', 'Benin', 'Benin', 'BEN', 204, 229);
INSERT INTO `aio_country` VALUES (24, 'BM', 'BERMUDA', 'Bermuda', 'Bermuda', 'BMU', 60, 1441);
INSERT INTO `aio_country` VALUES (25, 'BT', 'BHUTAN', 'Bhutan', 'Butan', 'BTN', 64, 975);
INSERT INTO `aio_country` VALUES (26, 'BO', 'BOLIVIA', 'Bolivia', 'Bolivya', 'BOL', 68, 591);
INSERT INTO `aio_country` VALUES (27, 'BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'Bosna Hersek', 'BIH', 70, 387);
INSERT INTO `aio_country` VALUES (28, 'BW', 'BOTSWANA', 'Botswana', 'Botsvana', 'BWA', 72, 267);
INSERT INTO `aio_country` VALUES (29, 'BV', 'BOUVET ISLAND', 'Bouvet Island', 'Bouvet Adası', NULL, NULL, 0);
INSERT INTO `aio_country` VALUES (30, 'BR', 'BRAZIL', 'Brazil', 'Brezilya', 'BRA', 76, 55);
INSERT INTO `aio_country` VALUES (31, 'IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', 'İngiliz Hint Okyanusu Bölgesi', NULL, NULL, 246);
INSERT INTO `aio_country` VALUES (32, 'BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'Brunei Sultanlığı', 'BRN', 96, 673);
INSERT INTO `aio_country` VALUES (33, 'BG', 'BULGARIA', 'Bulgaria', 'Bulgaristan', 'BGR', 100, 359);
INSERT INTO `aio_country` VALUES (34, 'BF', 'BURKINA FASO', 'Burkina Faso', 'Burkina Faso', 'BFA', 854, 226);
INSERT INTO `aio_country` VALUES (35, 'BI', 'BURUNDI', 'Burundi', 'Burundi', 'BDI', 108, 257);
INSERT INTO `aio_country` VALUES (36, 'KH', 'CAMBODIA', 'Cambodia', 'Kamboçya', 'KHM', 116, 855);
INSERT INTO `aio_country` VALUES (37, 'CM', 'CAMEROON', 'Cameroon', 'Kamerun', 'CMR', 120, 237);
INSERT INTO `aio_country` VALUES (38, 'CA', 'CANADA', 'Canada', 'Kanada', 'CAN', 124, 1);
INSERT INTO `aio_country` VALUES (39, 'CV', 'CAPE VERDE', 'Cape Verde', 'Cape Verde', 'CPV', 132, 238);
INSERT INTO `aio_country` VALUES (40, 'KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'Cayman Adaları', 'CYM', 136, 1345);
INSERT INTO `aio_country` VALUES (41, 'CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'Orta Afrika Cumhuriyeti', 'CAF', 140, 236);
INSERT INTO `aio_country` VALUES (42, 'TD', 'CHAD', 'Chad', 'Çad', 'TCD', 148, 235);
INSERT INTO `aio_country` VALUES (43, 'CL', 'CHILE', 'Chile', 'Şili', 'CHL', 152, 56);
INSERT INTO `aio_country` VALUES (44, 'CN', 'CHINA', 'China', 'Çin', 'CHN', 156, 86);
INSERT INTO `aio_country` VALUES (45, 'CX', 'CHRISTMAS ISLAND', 'Christmas Island', 'Noel Adası', NULL, NULL, 61);
INSERT INTO `aio_country` VALUES (46, 'CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Adaları', NULL, NULL, 672);
INSERT INTO `aio_country` VALUES (47, 'CO', 'COLOMBIA', 'Colombia', 'Kolombiya', 'COL', 170, 57);
INSERT INTO `aio_country` VALUES (48, 'KM', 'COMOROS', 'Comoros', 'Komorlar', 'COM', 174, 269);
INSERT INTO `aio_country` VALUES (49, 'CG', 'CONGO', 'Congo', 'Kongo', 'COG', 178, 242);
INSERT INTO `aio_country` VALUES (50, 'CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'Kongo, Demokratik Cumhuriyeti', 'COD', 180, 242);
INSERT INTO `aio_country` VALUES (51, 'CK', 'COOK ISLANDS', 'Cook Islands', 'Cook Adaları', 'COK', 184, 682);
INSERT INTO `aio_country` VALUES (52, 'CR', 'COSTA RICA', 'Costa Rica', 'Kosta Rika', 'CRI', 188, 506);
INSERT INTO `aio_country` VALUES (53, 'CI', 'COTE D\'IVOIRE', 'Cote D\'Ivoire', 'Fildişi Sahili', 'CIV', 384, 225);
INSERT INTO `aio_country` VALUES (54, 'HR', 'CROATIA', 'Croatia', 'Hırvatistan', 'HRV', 191, 385);
INSERT INTO `aio_country` VALUES (55, 'CU', 'CUBA', 'Cuba', 'Küba', 'CUB', 192, 53);
INSERT INTO `aio_country` VALUES (56, 'CY', 'CYPRUS', 'Cyprus', 'Kıbrıs', 'CYP', 196, 357);
INSERT INTO `aio_country` VALUES (57, 'CZ', 'CZECH REPUBLIC', 'Czech Republic', 'Çek Cumhuriyeti', 'CZE', 203, 420);
INSERT INTO `aio_country` VALUES (58, 'DK', 'DENMARK', 'Denmark', 'Danimarka', 'DNK', 208, 45);
INSERT INTO `aio_country` VALUES (59, 'DJ', 'DJIBOUTI', 'Djibouti', 'Cibuti', 'DJI', 262, 253);
INSERT INTO `aio_country` VALUES (60, 'DM', 'DOMINICA', 'Dominica', 'Dominika', 'DMA', 212, 1767);
INSERT INTO `aio_country` VALUES (61, 'DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'Dominik Cumhuriyeti', 'DOM', 214, 1809);
INSERT INTO `aio_country` VALUES (62, 'EC', 'ECUADOR', 'Ecuador', 'Ekvador', 'ECU', 218, 593);
INSERT INTO `aio_country` VALUES (63, 'EG', 'EGYPT', 'Egypt', 'Mısır', 'EGY', 818, 20);
INSERT INTO `aio_country` VALUES (64, 'SV', 'EL SALVADOR', 'El Salvador', 'El Salvador', 'SLV', 222, 503);
INSERT INTO `aio_country` VALUES (65, 'GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'Ekvator Ginesi', 'GNQ', 226, 240);
INSERT INTO `aio_country` VALUES (66, 'ER', 'ERITREA', 'Eritrea', 'Eritre', 'ERI', 232, 291);
INSERT INTO `aio_country` VALUES (67, 'EE', 'ESTONIA', 'Estonia', 'Estonya', 'EST', 233, 372);
INSERT INTO `aio_country` VALUES (68, 'ET', 'ETHIOPIA', 'Ethiopia', 'Etiyopya', 'ETH', 231, 251);
INSERT INTO `aio_country` VALUES (69, 'FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'Falkland Adaları (Malvinas)', 'FLK', 238, 500);
INSERT INTO `aio_country` VALUES (70, 'FO', 'FAROE ISLANDS', 'Faroe Islands', 'Faroe Adaları', 'FRO', 234, 298);
INSERT INTO `aio_country` VALUES (71, 'FJ', 'FIJI', 'Fiji', 'Fiji', 'FJI', 242, 679);
INSERT INTO `aio_country` VALUES (72, 'FI', 'FINLAND', 'Finland', 'Finlandiya', 'FIN', 246, 358);
INSERT INTO `aio_country` VALUES (73, 'FR', 'FRANCE', 'France', 'Fransa', 'FRA', 250, 33);
INSERT INTO `aio_country` VALUES (74, 'GF', 'FRENCH GUIANA', 'French Guiana', 'Fransız Guyanası', 'GUF', 254, 594);
INSERT INTO `aio_country` VALUES (75, 'PF', 'FRENCH POLYNESIA', 'French Polynesia', 'Fransız Polinezyası', 'PYF', 258, 689);
INSERT INTO `aio_country` VALUES (76, 'TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', 'Fransız Güney Toprakları', NULL, NULL, 0);
INSERT INTO `aio_country` VALUES (77, 'GA', 'GABON', 'Gabon', 'Gabon', 'GAB', 266, 241);
INSERT INTO `aio_country` VALUES (78, 'GM', 'GAMBIA', 'Gambia', 'Gambiya', 'GMB', 270, 220);
INSERT INTO `aio_country` VALUES (79, 'GE', 'GEORGIA', 'Georgia', 'Gürcistan', 'GEO', 268, 995);
INSERT INTO `aio_country` VALUES (80, 'DE', 'GERMANY', 'Germany', 'Almanya', 'DEU', 276, 49);
INSERT INTO `aio_country` VALUES (81, 'GH', 'GHANA', 'Ghana', 'Gana', 'GHA', 288, 233);
INSERT INTO `aio_country` VALUES (82, 'GI', 'GIBRALTAR', 'Gibraltar', 'Cebelitarık', 'GIB', 292, 350);
INSERT INTO `aio_country` VALUES (83, 'GR', 'GREECE', 'Greece', 'Yunanistan', 'GRC', 300, 30);
INSERT INTO `aio_country` VALUES (84, 'GL', 'GREENLAND', 'Greenland', 'Grönland', 'GRL', 304, 299);
INSERT INTO `aio_country` VALUES (85, 'GD', 'GRENADA', 'Grenada', 'Grenada', 'GRD', 308, 1473);
INSERT INTO `aio_country` VALUES (86, 'GP', 'GUADELOUPE', 'Guadeloupe', 'Guadeloupe', 'GLP', 312, 590);
INSERT INTO `aio_country` VALUES (87, 'GU', 'GUAM', 'Guam', 'Guam', 'GUM', 316, 1671);
INSERT INTO `aio_country` VALUES (88, 'GT', 'GUATEMALA', 'Guatemala', 'Guatemala', 'GTM', 320, 502);
INSERT INTO `aio_country` VALUES (89, 'GN', 'GUINEA', 'Guinea', 'Gine', 'GIN', 324, 224);
INSERT INTO `aio_country` VALUES (90, 'GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'Gine-Bissau', 'GNB', 624, 245);
INSERT INTO `aio_country` VALUES (91, 'GY', 'GUYANA', 'Guyana', 'Guyana', 'GUY', 328, 592);
INSERT INTO `aio_country` VALUES (92, 'HT', 'HAITI', 'Haiti', 'Haiti', 'HTI', 332, 509);
INSERT INTO `aio_country` VALUES (93, 'HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', 'Heard ve Mcdonald Adaları', NULL, NULL, 0);
INSERT INTO `aio_country` VALUES (94, 'VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'Kutsal Gör (Vatikan Şehir Devleti)', 'VAT', 336, 39);
INSERT INTO `aio_country` VALUES (95, 'HN', 'HONDURAS', 'Honduras', 'Honduras', 'HND', 340, 504);
INSERT INTO `aio_country` VALUES (96, 'HK', 'HONG KONG', 'Hong Kong', 'Hong Kong', 'HKG', 344, 852);
INSERT INTO `aio_country` VALUES (97, 'HU', 'HUNGARY', 'Hungary', 'Macaristan', 'HUN', 348, 36);
INSERT INTO `aio_country` VALUES (98, 'IS', 'ICELAND', 'Iceland', 'İzlanda', 'ISL', 352, 354);
INSERT INTO `aio_country` VALUES (99, 'IN', 'INDIA', 'India', 'Hindistan', 'IND', 356, 91);
INSERT INTO `aio_country` VALUES (100, 'ID', 'INDONESIA', 'Indonesia', 'Endonezya', 'IDN', 360, 62);
INSERT INTO `aio_country` VALUES (101, 'IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'İran, İslam Cumhuriyeti', 'IRN', 364, 98);
INSERT INTO `aio_country` VALUES (102, 'IQ', 'IRAQ', 'Iraq', 'Irak', 'IRQ', 368, 964);
INSERT INTO `aio_country` VALUES (103, 'IE', 'IRELAND', 'Ireland', 'İrlanda', 'IRL', 372, 353);
INSERT INTO `aio_country` VALUES (104, 'IL', 'ISRAEL', 'Israel', 'İsrail', 'ISR', 376, 972);
INSERT INTO `aio_country` VALUES (105, 'IT', 'ITALY', 'Italy', 'İtalya', 'ITA', 380, 39);
INSERT INTO `aio_country` VALUES (106, 'JM', 'JAMAICA', 'Jamaica', 'Jamaika', 'JAM', 388, 1876);
INSERT INTO `aio_country` VALUES (107, 'JP', 'JAPAN', 'Japan', 'Japonya', 'JPN', 392, 81);
INSERT INTO `aio_country` VALUES (108, 'JO', 'JORDAN', 'Jordan', 'Ürdün', 'JOR', 400, 962);
INSERT INTO `aio_country` VALUES (109, 'KZ', 'KAZAKHSTAN', 'Kazakhstan', 'Kazakistan', 'KAZ', 398, 7);
INSERT INTO `aio_country` VALUES (110, 'KE', 'KENYA', 'Kenya', 'Kenya', 'KEN', 404, 254);
INSERT INTO `aio_country` VALUES (111, 'KI', 'KIRIBATI', 'Kiribati', 'Kiribati', 'KIR', 296, 686);
INSERT INTO `aio_country` VALUES (112, 'KP', 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'Korea, Democratic People\'s Republic of', 'Kore Demokratik Halk Cumhuriyeti', 'PRK', 408, 850);
INSERT INTO `aio_country` VALUES (113, 'KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'Kore Cumhuriyeti', 'KOR', 410, 82);
INSERT INTO `aio_country` VALUES (114, 'KW', 'KUWAIT', 'Kuwait', 'Kuveyt', 'KWT', 414, 965);
INSERT INTO `aio_country` VALUES (115, 'KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'Kırgızistan', 'KGZ', 417, 996);
INSERT INTO `aio_country` VALUES (116, 'LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'Lao People\'s Democratic Republic', 'Lao Demokratik Halk Cumhuriyeti', 'LAO', 418, 856);
INSERT INTO `aio_country` VALUES (117, 'LV', 'LATVIA', 'Latvia', 'Letonya', 'LVA', 428, 371);
INSERT INTO `aio_country` VALUES (118, 'LB', 'LEBANON', 'Lebanon', 'Lübnan', 'LBN', 422, 961);
INSERT INTO `aio_country` VALUES (119, 'LS', 'LESOTHO', 'Lesotho', 'Lesotho', 'LSO', 426, 266);
INSERT INTO `aio_country` VALUES (120, 'LR', 'LIBERIA', 'Liberia', 'Liberya', 'LBR', 430, 231);
INSERT INTO `aio_country` VALUES (121, 'LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'Libya Arap Jamahiriya', 'LBY', 434, 218);
INSERT INTO `aio_country` VALUES (122, 'LI', 'LIECHTENSTEIN', 'Liechtenstein', 'Lihtenştayn', 'LIE', 438, 423);
INSERT INTO `aio_country` VALUES (123, 'LT', 'LITHUANIA', 'Lithuania', 'Litvanya', 'LTU', 440, 370);
INSERT INTO `aio_country` VALUES (124, 'LU', 'LUXEMBOURG', 'Luxembourg', 'Lüksemburg', 'LUX', 442, 352);
INSERT INTO `aio_country` VALUES (125, 'MO', 'MACAO', 'Macao', 'Macao', 'MAC', 446, 853);
INSERT INTO `aio_country` VALUES (126, 'MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'Makedonya, Eski Yugoslav Cumhuriyeti', 'MKD', 807, 389);
INSERT INTO `aio_country` VALUES (127, 'MG', 'MADAGASCAR', 'Madagascar', 'Madagaskar', 'MDG', 450, 261);
INSERT INTO `aio_country` VALUES (128, 'MW', 'MALAWI', 'Malawi', 'Malawi', 'MWI', 454, 265);
INSERT INTO `aio_country` VALUES (129, 'MY', 'MALAYSIA', 'Malaysia', 'Malezya', 'MYS', 458, 60);
INSERT INTO `aio_country` VALUES (130, 'MV', 'MALDIVES', 'Maldives', 'Maldivler', 'MDV', 462, 960);
INSERT INTO `aio_country` VALUES (131, 'ML', 'MALI', 'Mali', 'Mali', 'MLI', 466, 223);
INSERT INTO `aio_country` VALUES (132, 'MT', 'MALTA', 'Malta', 'Malta', 'MLT', 470, 356);
INSERT INTO `aio_country` VALUES (133, 'MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'Marşal Adaları', 'MHL', 584, 692);
INSERT INTO `aio_country` VALUES (134, 'MQ', 'MARTINIQUE', 'Martinique', 'Martinik', 'MTQ', 474, 596);
INSERT INTO `aio_country` VALUES (135, 'MR', 'MAURITANIA', 'Mauritania', 'Moritanya', 'MRT', 478, 222);
INSERT INTO `aio_country` VALUES (136, 'MU', 'MAURITIUS', 'Mauritius', 'Mauritius', 'MUS', 480, 230);
INSERT INTO `aio_country` VALUES (137, 'YT', 'MAYOTTE', 'Mayotte', 'Mayotte', NULL, NULL, 269);
INSERT INTO `aio_country` VALUES (138, 'MX', 'MEXICO', 'Mexico', 'Meksika', 'MEX', 484, 52);
INSERT INTO `aio_country` VALUES (139, 'FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'Mikronezya Federal Devletleri', 'FSM', 583, 691);
INSERT INTO `aio_country` VALUES (140, 'MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'Moldova Cumhuriyeti', 'MDA', 498, 373);
INSERT INTO `aio_country` VALUES (141, 'MC', 'MONACO', 'Monaco', 'Monako', 'MCO', 492, 377);
INSERT INTO `aio_country` VALUES (142, 'MN', 'MONGOLIA', 'Mongolia', 'Moğolistan', 'MNG', 496, 976);
INSERT INTO `aio_country` VALUES (143, 'MS', 'MONTSERRAT', 'Montserrat', 'Montserrat', 'MSR', 500, 1664);
INSERT INTO `aio_country` VALUES (144, 'MA', 'MOROCCO', 'Morocco', 'Fas', 'MAR', 504, 212);
INSERT INTO `aio_country` VALUES (145, 'MZ', 'MOZAMBIQUE', 'Mozambique', 'Mozambik', 'MOZ', 508, 258);
INSERT INTO `aio_country` VALUES (146, 'MM', 'MYANMAR', 'Myanmar', 'Myanmar', 'MMR', 104, 95);
INSERT INTO `aio_country` VALUES (147, 'NA', 'NAMIBIA', 'Namibia', 'Namibya', 'NAM', 516, 264);
INSERT INTO `aio_country` VALUES (148, 'NR', 'NAURU', 'Nauru', 'Nauru', 'NRU', 520, 674);
INSERT INTO `aio_country` VALUES (149, 'NP', 'NEPAL', 'Nepal', 'Nepal', 'NPL', 524, 977);
INSERT INTO `aio_country` VALUES (150, 'NL', 'NETHERLANDS', 'Netherlands', 'Hollanda', 'NLD', 528, 31);
INSERT INTO `aio_country` VALUES (151, 'AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'Hollanda Antilleri', 'ANT', 530, 599);
INSERT INTO `aio_country` VALUES (152, 'NC', 'NEW CALEDONIA', 'New Caledonia', 'Yeni Kaledonya', 'NCL', 540, 687);
INSERT INTO `aio_country` VALUES (153, 'NZ', 'NEW ZEALAND', 'New Zealand', 'Yeni Zelanda', 'NZL', 554, 64);
INSERT INTO `aio_country` VALUES (154, 'NI', 'NICARAGUA', 'Nicaragua', 'Nikaragua', 'NIC', 558, 505);
INSERT INTO `aio_country` VALUES (155, 'NE', 'NIGER', 'Niger', 'Nijer', 'NER', 562, 227);
INSERT INTO `aio_country` VALUES (156, 'NG', 'NIGERIA', 'Nigeria', 'Nijerya', 'NGA', 566, 234);
INSERT INTO `aio_country` VALUES (157, 'NU', 'NIUE', 'Niue', 'Niue', 'NIU', 570, 683);
INSERT INTO `aio_country` VALUES (158, 'NF', 'NORFOLK ISLAND', 'Norfolk Island', 'Norfolk Adası', 'NFK', 574, 672);
INSERT INTO `aio_country` VALUES (159, 'MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'Kuzey Mariana Adaları', 'MNP', 580, 1670);
INSERT INTO `aio_country` VALUES (160, 'NO', 'NORWAY', 'Norway', 'Norveç', 'NOR', 578, 47);
INSERT INTO `aio_country` VALUES (161, 'OM', 'OMAN', 'Oman', 'Umman', 'OMN', 512, 968);
INSERT INTO `aio_country` VALUES (162, 'PK', 'PAKISTAN', 'Pakistan', 'Pakistan', 'PAK', 586, 92);
INSERT INTO `aio_country` VALUES (163, 'PW', 'PALAU', 'Palau', 'Palau', 'PLW', 585, 680);
INSERT INTO `aio_country` VALUES (164, 'PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', 'Filistin Arazisi, İşgal altında', NULL, NULL, 970);
INSERT INTO `aio_country` VALUES (165, 'PA', 'PANAMA', 'Panama', 'Panama', 'PAN', 591, 507);
INSERT INTO `aio_country` VALUES (166, 'PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'Papua Yeni Gine', 'PNG', 598, 675);
INSERT INTO `aio_country` VALUES (167, 'PY', 'PARAGUAY', 'Paraguay', 'Paraguay', 'PRY', 600, 595);
INSERT INTO `aio_country` VALUES (168, 'PE', 'PERU', 'Peru', 'Peru', 'PER', 604, 51);
INSERT INTO `aio_country` VALUES (169, 'PH', 'PHILIPPINES', 'Philippines', 'Filipinler', 'PHL', 608, 63);
INSERT INTO `aio_country` VALUES (170, 'PN', 'PITCAIRN', 'Pitcairn', 'Pitcairn', 'PCN', 612, 0);
INSERT INTO `aio_country` VALUES (171, 'PL', 'POLAND', 'Poland', 'Polonya', 'POL', 616, 48);
INSERT INTO `aio_country` VALUES (172, 'PT', 'PORTUGAL', 'Portugal', 'Portekiz', 'PRT', 620, 351);
INSERT INTO `aio_country` VALUES (173, 'PR', 'PUERTO RICO', 'Puerto Rico', 'Porto Riko', 'PRI', 630, 1787);
INSERT INTO `aio_country` VALUES (174, 'QA', 'QATAR', 'Qatar', 'Katar', 'QAT', 634, 974);
INSERT INTO `aio_country` VALUES (175, 'RE', 'REUNION', 'Reunion', 'birleşme', 'REU', 638, 262);
INSERT INTO `aio_country` VALUES (176, 'RO', 'ROMANIA', 'Romania', 'Romanya', 'ROM', 642, 40);
INSERT INTO `aio_country` VALUES (177, 'RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'Rusya Federasyonu', 'RUS', 643, 70);
INSERT INTO `aio_country` VALUES (178, 'RW', 'RWANDA', 'Rwanda', 'Ruanda', 'RWA', 646, 250);
INSERT INTO `aio_country` VALUES (179, 'SH', 'SAINT HELENA', 'Saint Helena', 'Saint Helena', 'SHN', 654, 290);
INSERT INTO `aio_country` VALUES (180, 'KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'Saint Kitts ve Nevis', 'KNA', 659, 1869);
INSERT INTO `aio_country` VALUES (181, 'LC', 'SAINT LUCIA', 'Saint Lucia', 'Saint Lucia', 'LCA', 662, 1758);
INSERT INTO `aio_country` VALUES (182, 'PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'Saint Pierre ve Miquelon', 'SPM', 666, 508);
INSERT INTO `aio_country` VALUES (183, 'VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'Saint Vincent ve Grenadinler', 'VCT', 670, 1784);
INSERT INTO `aio_country` VALUES (184, 'WS', 'SAMOA', 'Samoa', 'Samoa', 'WSM', 882, 684);
INSERT INTO `aio_country` VALUES (185, 'SM', 'SAN MARINO', 'San Marino', 'San Marino', 'SMR', 674, 378);
INSERT INTO `aio_country` VALUES (186, 'ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'Sao Tome ve Principe', 'STP', 678, 239);
INSERT INTO `aio_country` VALUES (187, 'SA', 'SAUDI ARABIA', 'Saudi Arabia', 'Suudi Arabistan', 'SAU', 682, 966);
INSERT INTO `aio_country` VALUES (188, 'SN', 'SENEGAL', 'Senegal', 'Senegal', 'SEN', 686, 221);
INSERT INTO `aio_country` VALUES (189, 'CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', 'Sırbistan ve Karadağ', NULL, NULL, 381);
INSERT INTO `aio_country` VALUES (190, 'SC', 'SEYCHELLES', 'Seychelles', 'Seyşeller', 'SYC', 690, 248);
INSERT INTO `aio_country` VALUES (191, 'SL', 'SIERRA LEONE', 'Sierra Leone', 'Sierra Leone', 'SLE', 694, 232);
INSERT INTO `aio_country` VALUES (192, 'SG', 'SINGAPORE', 'Singapore', 'Singapur', 'SGP', 702, 65);
INSERT INTO `aio_country` VALUES (193, 'SK', 'SLOVAKIA', 'Slovakia', 'Slovakya', 'SVK', 703, 421);
INSERT INTO `aio_country` VALUES (194, 'SI', 'SLOVENIA', 'Slovenia', 'Slovenya', 'SVN', 705, 386);
INSERT INTO `aio_country` VALUES (195, 'SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'Solomon Adaları', 'SLB', 90, 677);
INSERT INTO `aio_country` VALUES (196, 'SO', 'SOMALIA', 'Somalia', 'Somali', 'SOM', 706, 252);
INSERT INTO `aio_country` VALUES (197, 'ZA', 'SOUTH AFRICA', 'South Africa', 'Güney Afrika', 'ZAF', 710, 27);
INSERT INTO `aio_country` VALUES (198, 'GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', 'Güney Georgia ve Güney Sandwich Adaları', NULL, NULL, 0);
INSERT INTO `aio_country` VALUES (199, 'ES', 'SPAIN', 'Spain', 'ispanya', 'ESP', 724, 34);
INSERT INTO `aio_country` VALUES (200, 'LK', 'SRI LANKA', 'Sri Lanka', 'Sri Lanka', 'LKA', 144, 94);
INSERT INTO `aio_country` VALUES (201, 'SD', 'SUDAN', 'Sudan', 'Sudan', 'SDN', 736, 249);
INSERT INTO `aio_country` VALUES (202, 'SR', 'SURINAME', 'Suriname', 'Surinam', 'SUR', 740, 597);
INSERT INTO `aio_country` VALUES (203, 'SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'Svalbard ve Jan Mayen', 'SJM', 744, 47);
INSERT INTO `aio_country` VALUES (204, 'SZ', 'SWAZILAND', 'Swaziland', 'Svaziland', 'SWZ', 748, 268);
INSERT INTO `aio_country` VALUES (205, 'SE', 'SWEDEN', 'Sweden', 'İsveç', 'SWE', 752, 46);
INSERT INTO `aio_country` VALUES (206, 'CH', 'SWITZERLAND', 'Switzerland', 'İsviçre', 'CHE', 756, 41);
INSERT INTO `aio_country` VALUES (207, 'SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'Suriye Arap Cumhuriyeti', 'SYR', 760, 963);
INSERT INTO `aio_country` VALUES (208, 'TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'Tayvan, Çin\'in bölgesi', 'TWN', 158, 886);
INSERT INTO `aio_country` VALUES (209, 'TJ', 'TAJIKISTAN', 'Tajikistan', 'Tacikistan', 'TJK', 762, 992);
INSERT INTO `aio_country` VALUES (210, 'TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'Tanzanya, Birleşik Cumhuriyeti', 'TZA', 834, 255);
INSERT INTO `aio_country` VALUES (211, 'TH', 'THAILAND', 'Thailand', 'Tayland', 'THA', 764, 66);
INSERT INTO `aio_country` VALUES (212, 'TL', 'TIMOR-LESTE', 'Timor-Leste', 'Timor-Leste', NULL, NULL, 670);
INSERT INTO `aio_country` VALUES (213, 'TG', 'TOGO', 'Togo', 'Gitmek', 'TGO', 768, 228);
INSERT INTO `aio_country` VALUES (214, 'TK', 'TOKELAU', 'Tokelau', 'Tokelau', 'TKL', 772, 690);
INSERT INTO `aio_country` VALUES (215, 'TO', 'TONGA', 'Tonga', 'Tonga', 'TON', 776, 676);
INSERT INTO `aio_country` VALUES (216, 'TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'Trinidad ve Tobago', 'TTO', 780, 1868);
INSERT INTO `aio_country` VALUES (217, 'TN', 'TUNISIA', 'Tunisia', 'Tunus', 'TUN', 788, 216);
INSERT INTO `aio_country` VALUES (218, 'TR', 'TURKEY', 'Turkey', 'Türkiye', 'TUR', 792, 90);
INSERT INTO `aio_country` VALUES (219, 'TM', 'TURKMENISTAN', 'Turkmenistan', 'Türkmenistan', 'TKM', 795, 7370);
INSERT INTO `aio_country` VALUES (220, 'TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'Turks ve Caicos Adaları', 'TCA', 796, 1649);
INSERT INTO `aio_country` VALUES (221, 'TV', 'TUVALU', 'Tuvalu', 'Tuvalu', 'TUV', 798, 688);
INSERT INTO `aio_country` VALUES (222, 'UG', 'UGANDA', 'Uganda', 'Uganda', 'UGA', 800, 256);
INSERT INTO `aio_country` VALUES (223, 'UA', 'UKRAINE', 'Ukraine', 'Ukrayna', 'UKR', 804, 380);
INSERT INTO `aio_country` VALUES (224, 'AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'Birleşik Arap Emirlikleri', 'ARE', 784, 971);
INSERT INTO `aio_country` VALUES (225, 'GB', 'UNITED KINGDOM', 'United Kingdom', 'Birleşik Krallık', 'GBR', 826, 44);
INSERT INTO `aio_country` VALUES (226, 'US', 'UNITED STATES', 'United States', 'Amerika Birleşik Devletleri', 'USA', 840, 1);
INSERT INTO `aio_country` VALUES (227, 'UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', 'Amerika Birleşik Devletleri Küçük Dış Adaları', NULL, NULL, 1);
INSERT INTO `aio_country` VALUES (228, 'UY', 'URUGUAY', 'Uruguay', 'Uruguay', 'URY', 858, 598);
INSERT INTO `aio_country` VALUES (229, 'UZ', 'UZBEKISTAN', 'Uzbekistan', 'Özbekistan', 'UZB', 860, 998);
INSERT INTO `aio_country` VALUES (230, 'VU', 'VANUATU', 'Vanuatu', 'Vanuatu', 'VUT', 548, 678);
INSERT INTO `aio_country` VALUES (231, 'VE', 'VENEZUELA', 'Venezuela', 'Venezuela', 'VEN', 862, 58);
INSERT INTO `aio_country` VALUES (232, 'VN', 'VIET NAM', 'Viet Nam', 'Vietnam', 'VNM', 704, 84);
INSERT INTO `aio_country` VALUES (233, 'VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'Virgin Adaları, İngiliz', 'VGB', 92, 1284);
INSERT INTO `aio_country` VALUES (234, 'VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'Virgin Adaları, ABD', 'VIR', 850, 1340);
INSERT INTO `aio_country` VALUES (235, 'WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'Wallis ve Futuna', 'WLF', 876, 681);
INSERT INTO `aio_country` VALUES (236, 'EH', 'WESTERN SAHARA', 'Western Sahara', 'Batı Sahra', 'ESH', 732, 212);
INSERT INTO `aio_country` VALUES (237, 'YE', 'YEMEN', 'Yemen', 'Yemen', 'YEM', 887, 967);
INSERT INTO `aio_country` VALUES (238, 'ZM', 'ZAMBIA', 'Zambia', 'Zambiya', 'ZMB', 894, 260);
INSERT INTO `aio_country` VALUES (239, 'ZW', 'ZIMBABWE', 'Zimbabwe', 'Zimbabve', 'ZWE', 716, 263);

SET FOREIGN_KEY_CHECKS = 1;
